# engines_data.py

engines = {
    'General': {
        'Google': 'https://www.google.com/search?q={}',
        'Bing': 'https://www.bing.com/search?q={}',
        'GoogleUS': 'https://www.google.com/search?q={}&gl=us&hl=en',
    },
    'Video footage': {
        'Coverr': 'https://coverr.co/s?q={}',
        'Pexels video': 'https://www.pexels.com/zh-tw/search/videos/{}/', 
        'Youtube': 'https://www.youtube.com/results?search_query={}',
        'Cute Stock Footage': 'https://cutestockfootage.com/?s={}',
        'Dareful': 'https://dareful.com/?s={}',
        'All-free-download video': 'https://all-free-download.com/free-footage/{}.html',
        'Dissolve': 'https://dissolve.com/creators/content/search/video-image/downloadable/{}',
        'Freestock video': 'https://www.freestock.com/search/{}?type=videos',
        'Isorepublic video': 'https://isorepublic.com/?s={}&post_type=video_post',
        'Bing video': 'https://www.bing.com/videos/search?q={}',
        'Google video': 'https://www.google.com/search?q={}&tbm=vid',
        'Mazwai': 'https://mazwai.com/search/{}',
        'Monzoom video': 'https://www.monzoom.com/?search={}&svideo=on',
        'Orangehd': 'https://www.orangehd.com/?s={}',
        'Pikwizard video': 'https://pikwizard.com/search/?query={}&assetType=video',
        'Pixabay video': 'https://pixabay.com/videos/search/{}/',
        'Motionarray': 'https://motionarray.com/browse/stock-video/free/?q={}',
        'Stockio video': 'https://www.stockio.com/free-videos/?q={}',
        'Vecteezy video': 'https://www.vecteezy.com/free-videos/{}?license-free=true',
        'Pinterest video': 'https://www.pinterest.com/search/videos/?q={}&rs=filter',
        'Videezy': 'https://www.videezy.com/free-video/{}?license-cc=true&license-standard=true&from=mainsite&in_se=true',
        'Videvo': 'https://www.videvo.net/search/?q={}&mode=video&type[0]=free',
        'Vidsplay': 'https://www.vidsplay.com/?s={}',
        'Europeana': 'https://www.europeana.eu/en/search?page=1&qf=TYPE%3A%22VIDEO%22&query={}%20AND%20RIGHTS%3A%2Acreative%2A%20AND%20NOT%20RIGHTS%3A%2Anc%2A%20AND%20NOT%20RIGHTS%3A%2And%2A&view=grid',
        'Flickr video': 'https://flickr.com/search/?text={}&license=4%2C5%2C9%2C10&video_content_types=0%2C1%2C2%2C3',
        'Vimeo': 'https://vimeo.com/search?&q={}&license=by',
        'Tiktok': 'https://www.tiktok.com/search?q={}',
        'Giphy': 'https://giphy.com/search/{}',
        'Facebook': 'https://www.facebook.com/watch/search/?q={}',
        'Steam': 'https://store.steampowered.com/search/?sort_by=_ASC&term={}&supportedlang=english%2Cschinese%2Ctchinese%2Cjapanese',
        'Epicgames': 'https://store.epicgames.com/zh-Hant/browse?q={}&sortBy=relevancy&sortDir=DESC&count=40','6huo': 'https://www.6huo.com/?keyword={}&view=search',
        'IMDB': 'https://www.imdb.com/find/?q={}',
        #'Zhaotaici': 'https://zhaotaici.cn/?query={}',
        'Freepik video':'https://www.freepik.com/search?format=search&last_filter=type&last_value=video&query={}&selection=1&type=video',
        #'Mixkit video': 'https://mixkit.co/free-stock-video/{}/',        
        'Video-ac': 'https://video-ac.com/video/discovery?search={}',
        'Yandex video': 'https://yandex.com/video/search?text={}&where=all',
    },
    'News': {
        'CNN': 'https://www.cnn.com/search?q={}',
        'BBC': 'https://www.bbc.co.uk/search?q={}',
    },
    'EC': {
        'BigGo': 'https://biggo.com.tw/s/{}/?sort=lp&view=list',
        'FindPrice': 'https://www.findprice.com.tw/g/{}/?o=1',
        'GYM': 'https://www.goyomoney.com.tw/search?order=asc&orderBy=price&pageIndex=0&queryText={}',
        'feebee': 'https://feebee.com.tw/s/{}/?sort=p',
    },
    'Image material': {
        'Bucketlistly': 'https://www.bucketlistly.blog/photos/photo-search?search={}',
        'Barnimages': 'https://barnimages.com/?s={}',
        'Shopify': 'https://burst.shopify.com/photos/search?q={}',
        'Designerspics': 'http://www.designerspics.com/?s={}',
        '1001freedownloads': 'https://www.1001freedownloads.com/?q={}',
        'Foodiesfeed': 'https://www.foodiesfeed.com/?s={}',
        'Footagecrate': 'https://footagecrate.com/',
        'GraphicsCrate': 'https://graphics.productioncrate.com/search/#!/cat',
        'All-free-download photos': 'https://all-free-download.com/free-photos/{}.html',
        'Freenaturestock': 'https://freenaturestock.com/?s={}',
        'Rawpixel': 'https://www.rawpixel.com/search/{}?page=1&sort=curated&topic_group=_topics',
        'Freeimages': 'https://www.freeimages.com/cn/search/money',
        'Freepik photo': 'https://www.freepik.com/search?format=search&last_filter=selection&last_value=1&query={}&selection=1&type=photo',
        'Freestock photo': 'https://www.freestock.com/search/{}?type=photos',
        'Gratisography': 'https://gratisography.com/?s={}',
        'Isorepublic': 'https://isorepublic.com/?s={}&post_type=photo_post',
        'Kaboompics': 'https://kaboompics.com/gallery?search={}',
        'Libreshot': 'https://libreshot.com/?s={}',
        'Lifeofpix': 'https://www.lifeofpix.com/search/{}?',
        'Magdelein': 'https://magdeleine.co/?s={}',
        'Moveast': 'https://moveast.me/search/{}',
        'Mystock': 'https://mystock.themeisle.com/?s={}&tag=',
        'Negativespace': 'https://negativespace.co/?s={}',
        'New Old Stock': 'https://nos.twnsnd.co/search/{}',
        'The Noun Project': 'https://thenounproject.com/search/photos/?q={}',
        'Pexels photo': 'https://www.pexels.com/zh-tw/search/{}/',
        'Photo-ac': 'https://zh-tw.photo-ac.com/search/{}?page=1&color=all&modelCount=-2&orderBy=random&shape=all',
        'Photock': 'https://www.photock.org/list/s/search/?name={}',
        'Picjumbo': 'https://picjumbo.com/search/{}',
        'Picography': 'https://picography.co/search/cat',
        'Pikwizard photo': 'https://pikwizard.com/search/?query=cat&assetType=photo',
        'Piqsels': 'https://www.piqsels.com/en/search?q=cat',
        'Pixabay photo': 'https://pixabay.com/photos/search/{}/',
        'Realisticshots': 'https://realisticshots.com/search/{}',
        'Rgbstock': 'https://www.rgbstock.com/images/{}',
        'Shotstash': 'https://shotstash.com/?s={}',
        'Skitterphoto': 'https://skitterphoto.com/photos/search/{}',
        'Startupstockphotos': 'https://startupstockphotos.com/?s=cat',
        'Stockio photo': 'https://www.stockio.com/free-photos/?q={}',
        'Stocksnap': 'https://stocksnap.io/search/{}',
        'Stockvault': 'https://www.stockvault.net/free-photos/{}/',
        'Streetwill': 'http://streetwill.co/posts/search?q={}',
        'Styledstock': 'https://styledstock.co/?s={}&post_type=product',
        'Unsplash': 'https://unsplash.com/s/photos/{}',
        'Vecteezy photo': 'https://www.vecteezy.com/free-photos/cat?license-free=true',
        'Wunderstock': 'https://wunderstock.com/?s={}',
        'Pakutas': 'https://www.pakutaso.com/search.html?offset=0&limit=20&search={}',
        'Photosku': 'https://photosku.com/search/?t=photo&s={}',
        '123RF': 'https://tw.123rf.com/%E5%85%8D%E8%B2%BB%E5%9C%96%E5%BA%AB%E7%85%A7%E7%89%87/{}.html?safe_search=0',
        'Flickr photo': 'https://flickr.com/search/?license=4%2C5%2C9%2C10&text={}&content_types=0',
        'Bing image': 'https://www.bing.com/images/search?q={}',
        'Google image': 'https://www.google.com/search?q={}&tbm=isch',
        'Pinterest': 'https://www.pinterest.com/search/pins/?q=cat&rs=typed',
        'Behance': 'https://www.behance.net/search/projects?search={}&tracking_source=typeahead_nav_recent_suggestion',
        'Lexica': 'https://lexica.art/?q={}',
        'Nightcafe': 'https://creator.nightcafe.studio/search/creations?q={}',
        'Yandex image': 'https://yandex.com/images/search?text={}',
    }
}